id: P006745
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:20:38.570497
source_metadata:
  id: bdr:W29495
  title: བོད་ཀྱི་བརྡ་རྙིང་ཡིག་ཆ་རྩ་ཆེན་བདམས་བསྒྲིགས་རྣམས་ཀྱི་ཚིག་དོན་ཀུན་ནས་ཁྲོལ་བར་བྱས་པ་རབ་གསལ་མེ་ལོང
  author: ''
  volumes:
    a822490ecaa24fea8ef1c5e5fb697466:
      image_group_id: I1KG5902
      title: ''
      volume_number: 1
      total_pages: 486
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
