id: P006745
initial_creation_type: ocr
source_metadata:
  id: bdr:W29495
  title: བོད་ཀྱི་བརྡ་རྙིང་ཡིག་ཆ་རྩ་ཆེན་བདམས་བསྒྲིགས་རྣམས་ཀྱི་ཚིག་དོན་ཀུན་ནས་ཁྲོལ་བར་བྱས་པ་རབ་གསལ་མེ་ལོང
  author: ''
  volumes: {}
